# Generated by Django 4.2.1 on 2023-05-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='adress',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
